export interface CryptoCurrency {
  id: string
  name: string
  symbol: string
  logo: string
  marketCap: string
  volume24h: string
  bullishPercentage: number
  tradingViewSymbol: string
  change24h: string
  bullishVotes: number
  bearishVotes: number
}

export const cryptoList: CryptoCurrency[] = [
  {
    id: "bitcoin",
    name: "Bitcoin",
    symbol: "BTC",
    logo: "https://assets.coingecko.com/coins/images/1/large/bitcoin.png?1547033579",
    marketCap: "$1.2T",
    volume24h: "$35.4B",
    bullishPercentage: 65,
    tradingViewSymbol: "BINANCE:BTCUSDT",
    change24h: "+1.2%",
    bullishVotes: 452,
    bearishVotes: 243,
  },
  {
    id: "ethereum",
    name: "Ethereum",
    symbol: "ETH",
    logo: "https://assets.coingecko.com/coins/images/279/large/ethereum.png?1595348880",
    marketCap: "$360B",
    volume24h: "$20.1B",
    bullishPercentage: 55,
    tradingViewSymbol: "BINANCE:ETHUSDT",
    change24h: "-0.8%",
    bullishVotes: 387,
    bearishVotes: 316,
  },
  {
    id: "solana",
    name: "Solana",
    symbol: "SOL",
    logo: "https://assets.coingecko.com/coins/images/4128/large/solana.png?1640133422",
    marketCap: "$42.1B",
    volume24h: "$2.1B",
    bullishPercentage: 72,
    tradingViewSymbol: "BINANCE:SOLUSDT",
    change24h: "+2.3%",
    bullishVotes: 343,
    bearishVotes: 103,
  },
  {
    id: "xrp",
    name: "XRP",
    symbol: "XRP",
    logo: "https://assets.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1605778731",
    marketCap: "$35.2B",
    volume24h: "$1.8B",
    bullishPercentage: 61,
    tradingViewSymbol: "BINANCE:XRPUSDT",
    change24h: "+0.7%",
    bullishVotes: 298,
    bearishVotes: 190,
  },
  {
    id: "binancecoin",
    name: "BNB",
    symbol: "BNB",
    logo: "https://assets.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1644979850",
    marketCap: "$48.2B",
    volume24h: "$1.2B",
    bullishPercentage: 58,
    tradingViewSymbol: "BINANCE:BNBUSDT",
    change24h: "+0.5%",
    bullishVotes: 276,
    bearishVotes: 200,
  },
  {
    id: "cardano",
    name: "Cardano",
    symbol: "ADA",
    logo: "https://assets.coingecko.com/coins/images/975/large/cardano.png?1547034860",
    marketCap: "$20.5B",
    volume24h: "$850M",
    bullishPercentage: 48,
    tradingViewSymbol: "BINANCE:ADAUSDT",
    change24h: "-1.2%",
    bullishVotes: 198,
    bearishVotes: 214,
  },
  {
    id: "avalanche",
    name: "Avalanche",
    symbol: "AVAX",
    logo: "https://assets.coingecko.com/coins/images/12559/large/Avalanche_Circle_RedWhite_Trans.png?1670992574",
    marketCap: "$15.8B",
    volume24h: "$720M",
    bullishPercentage: 62,
    tradingViewSymbol: "BINANCE:AVAXUSDT",
    change24h: "+1.8%",
    bullishVotes: 245,
    bearishVotes: 150,
  },
  {
    id: "dogecoin",
    name: "Dogecoin",
    symbol: "DOGE",
    logo: "https://assets.coingecko.com/coins/images/5/large/dogecoin.png?1547792256",
    marketCap: "$12.1B",
    volume24h: "$580M",
    bullishPercentage: 59,
    tradingViewSymbol: "BINANCE:DOGEUSDT",
    change24h: "-0.4%",
    bullishVotes: 234,
    bearishVotes: 163,
  },
  {
    id: "polkadot",
    name: "Polkadot",
    symbol: "DOT",
    logo: "https://assets.coingecko.com/coins/images/12171/large/polkadot.png?1639712644",
    marketCap: "$9.8B",
    volume24h: "$420M",
    bullishPercentage: 45,
    tradingViewSymbol: "BINANCE:DOTUSDT",
    change24h: "-0.9%",
    bullishVotes: 167,
    bearishVotes: 204,
  },
  {
    id: "chainlink",
    name: "Chainlink",
    symbol: "LINK",
    logo: "https://assets.coingecko.com/coins/images/877/large/chainlink-new-logo.png?1547034700",
    marketCap: "$8.9B",
    volume24h: "$380M",
    bullishPercentage: 68,
    tradingViewSymbol: "BINANCE:LINKUSDT",
    change24h: "+1.5%",
    bullishVotes: 289,
    bearishVotes: 136,
  },
  {
    id: "polygon",
    name: "Polygon",
    symbol: "MATIC",
    logo: "https://assets.coingecko.com/coins/images/4713/large/matic-token-icon.png?1624446912",
    marketCap: "$7.2B",
    volume24h: "$310M",
    bullishPercentage: 70,
    tradingViewSymbol: "BINANCE:MATICUSDT",
    change24h: "+2.1%",
    bullishVotes: 312,
    bearishVotes: 134,
  },
  {
    id: "shiba-inu",
    name: "Shiba Inu",
    symbol: "SHIB",
    logo: "https://assets.coingecko.com/coins/images/11939/large/shiba.png?1622619446",
    marketCap: "$6.9B",
    volume24h: "$290M",
    bullishPercentage: 57,
    tradingViewSymbol: "BINANCE:SHIBUSDT",
    change24h: "-1.3%",
    bullishVotes: 245,
    bearishVotes: 185,
  },
  {
    id: "litecoin",
    name: "Litecoin",
    symbol: "LTC",
    logo: "https://assets.coingecko.com/coins/images/2/large/litecoin.png?1547033580",
    marketCap: "$5.8B",
    volume24h: "$250M",
    bullishPercentage: 63,
    tradingViewSymbol: "BINANCE:LTCUSDT",
    change24h: "+0.9%",
    bullishVotes: 267,
    bearishVotes: 157,
  },
  {
    id: "uniswap",
    name: "Uniswap",
    symbol: "UNI",
    logo: "https://assets.coingecko.com/coins/images/12504/large/uniswap-uni.png?1600306604",
    marketCap: "$4.8B",
    volume24h: "$280M",
    bullishPercentage: 59,
    tradingViewSymbol: "BINANCE:UNIUSDT",
    change24h: "-0.7%",
    bullishVotes: 245,
    bearishVotes: 170,
  },
  {
    id: "bitcoin-cash",
    name: "Bitcoin Cash",
    symbol: "BCH",
    logo: "https://assets.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png?1594689492",
    marketCap: "$4.2B",
    volume24h: "$220M",
    bullishPercentage: 56,
    tradingViewSymbol: "BINANCE:BCHUSDT",
    change24h: "-0.5%",
    bullishVotes: 234,
    bearishVotes: 184,
  },
  {
    id: "cosmos",
    name: "Cosmos",
    symbol: "ATOM",
    logo: "https://assets.coingecko.com/coins/images/1481/large/cosmos_hub.png?1555657960",
    marketCap: "$3.2B",
    volume24h: "$190M",
    bullishPercentage: 57,
    tradingViewSymbol: "BINANCE:ATOMUSDT",
    change24h: "-1.5%",
    bullishVotes: 234,
    bearishVotes: 176,
  },
  {
    id: "monero",
    name: "Monero",
    symbol: "XMR",
    logo: "https://assets.coingecko.com/coins/images/69/large/monero_logo.png?1547033729",
    marketCap: "$2.8B",
    volume24h: "$160M",
    bullishPercentage: 69,
    tradingViewSymbol: "BINANCE:XMRUSDT",
    change24h: "+1.4%",
    bullishVotes: 312,
    bearishVotes: 140,
  },
  {
    id: "stellar",
    name: "Stellar",
    symbol: "XLM",
    logo: "https://assets.coingecko.com/coins/images/100/large/Stellar_symbol_black_RGB.png?1552356157",
    marketCap: "$3.5B",
    volume24h: "$180M",
    bullishPercentage: 54,
    tradingViewSymbol: "BINANCE:XLMUSDT",
    change24h: "-0.3%",
    bullishVotes: 245,
    bearishVotes: 209,
  },
  {
    id: "near",
    name: "NEAR Protocol",
    symbol: "NEAR",
    logo: "https://assets.coingecko.com/coins/images/10365/large/near_icon.png?1601359077",
    marketCap: "$1.8B",
    volume24h: "$140M",
    bullishPercentage: 66,
    tradingViewSymbol: "BINANCE:NEARUSDT",
    change24h: "+1.7%",
    bullishVotes: 267,
    bearishVotes: 138,
  },
  {
    id: "fantom",
    name: "Fantom",
    symbol: "FTM",
    logo: "https://assets.coingecko.com/coins/images/4001/large/Fantom.png?1558015016",
    marketCap: "$1.5B",
    volume24h: "$130M",
    bullishPercentage: 63,
    tradingViewSymbol: "BINANCE:FTMUSDT",
    change24h: "+2.2%",
    bullishVotes: 289,
    bearishVotes: 170,
  },
]

